apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kopdar
  labels:
    label-key1: label-value1
  annotations:
    annotation-key1: annotation-value1
spec:
  replicas: 3
  selector:
    matchLabels:
      label-key1: label-value1
  template:
    metadata:
      name: kopdar-pod
      labels:
        label-key1: label-value1
    spec:
      containers:
      - name: container-feast
        image: services_feast
        ports:
        - containerPort: 4002
        readinessProbe:
          httpGet:
            path: /health
            port: 4002
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
      - name: container-futsal
        image: services_futsal
        ports:
        - containerPort: 4003
        readinessProbe:
          httpGet:
            path: /health
            port: 4003
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
      - name: container-watching
        image: services_watching
        ports:
        - containerPort: 4004
        readinessProbe:
          httpGet:
            path: /health
            port: 4004
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1