apiVersion: v1
kind: Pod
metadata:
  name: kopdar-pod
spec:
  containers:
    - name: container-feast
      image: services_feast
      ports:
        - containerPort: 4002
    - name: container-futsal
      image: services_futsal
      ports:
        - containerPort: 4003
    - name: container-watching
      image: services_watching
      ports:
        - containerPort: 4004